Repository goharbor/harbor-helm, pull requests merged in 2019-12, with the labels that each got.

#452 Upgrade kubernetes API version
  templates/nginx/deployment.yaml
Labels: target/1.2.4

#466 Add commands for helm3 in doc
  README.md
  docs/High Availability.md
Labels: target/1.3.0

#455 Add fsGroup for registry, chartmuseum and clair
  templates/chartmuseum/chartmuseum-dpl.yaml
  templates/clair/clair-dpl.yaml
  templates/registry/registry-dpl.yaml
Labels: target/1.3.0

#451 Add comment for log level and update the mantainers
  Chart.yaml
  README.md
  values.yaml
Labels: target/1.3.0

#463 Provide the configuration item xsrf key in values.yaml
  README.md
  templates/core/core-cm.yaml
  values.yaml
Labels: target/1.2.4

#470 Provide the update strategy for deployments with persistent volumes in values.yaml
  README.md
  templates/chartmuseum/chartmuseum-dpl.yaml
  templates/jobservice/jobservice-dpl.yaml
  templates/registry/registry-dpl.yaml
  values.yaml
Labels: target/1.3.0

#462 Provide the configuration item xsrf key in values.yaml
  README.md
  templates/core/core-cm.yaml
  values.yaml
Labels: target/1.3.0

#472 Bump up Harbor version to 1.10.0
  Chart.yaml
  values.yaml
Labels: target/1.3.0

#471 Update the comment to the xsrfkey
  README.md
  values.yaml
Labels: target/1.2.0

#478 Reduce log level to info - cherry pick to 1.2
  README.md
  values.yaml
Labels: target/1.2.4

#477 Make the image of the init container for database configurable - cherry pick to 1.2
  README.md
  templates/database/database-ss.yaml
  values.yaml
Labels: target/1.2.4
