Repository goharbor/harbor-helm, pull requests merged in 2020-12, with the labels that each got.

#784 Fix ingress paths for ingress-nginx 0.41.0
  templates/ingress/ingress.yaml
Labels: target/1.6.0

#745 Fix random CI failure in Github action
  docs/High Availability.md
  docs/Upgrade.md
  test/integration/base.go
Labels: target/1.6.0

#781 Make startupProbe optional
  templates/core/core-dpl.yaml
  values.yaml
Labels: target/1.5.2, target/1.6.0

#801 [cherry-pick] fix(chartmuseum) compatible s3 cache fail for 1.5.2
  templates/chartmuseum/chartmuseum-cm.yaml
Labels: target/1.5.2

#813 Bump up OSS Harbor to v2.1.2
  Chart.yaml
  values.yaml
Labels: target/1.5.2

#812 Backport several fixes into the 1.5 branch
  templates/core/core-dpl.yaml
  templates/ingress/ingress.yaml
  values.yaml
Labels: target/1.5.2

#799 fix(chartmuseum) compatible s3 cache fail
  templates/chartmuseum/chartmuseum-cm.yaml
Labels: target/1.6.0

#791 Configure notary deployments at server/signer level
  templates/notary/notary-server.yaml
  templates/notary/notary-signer.yaml
  values.yaml
Labels: target/1.6.0

#768 Disable mounting serviceAccount credentials from pods
  templates/chartmuseum/chartmuseum-dpl.yaml
  templates/clair/clair-dpl.yaml
  templates/core/core-dpl.yaml
  templates/database/database-ss.yaml
  templates/jobservice/jobservice-dpl.yaml
  templates/notary/notary-server.yaml
  templates/notary/notary-signer.yaml
  templates/portal/deployment.yaml
  templates/redis/statefulset.yaml
  templates/registry/registry-dpl.yaml
Labels: target/1.6.0
