Repository goharbor/harbor-helm, pull requests merged in 2021-03, with the labels that each got.

#862 Add http proxy to registryctl container
  templates/registry/registry-dpl.yaml
Labels: target/1.6.1, target/1.7.0

#893 Add another init container for database to ensure the permission of data directory
  templates/database/database-ss.yaml
Labels: target/1.5.4, target/1.6.1

#870 fix: make the reference to the jobloggers array consistent
  README.md
  docs/High Availability.md
  templates/jobservice/jobservice-dpl.yaml
Labels: target/1.6.1, target/1.7.0

#904 Backport the PSP support fixes and bump up OSS Harbor to 2.1.4
  Chart.yaml
  templates/chartmuseum/chartmuseum-dpl.yaml
  templates/clair/clair-dpl.yaml
  templates/core/core-dpl.yaml
  templates/database/database-ss.yaml
  templates/jobservice/jobservice-dpl.yaml
  templates/nginx/deployment.yaml
  templates/notary/notary-server.yaml
  templates/notary/notary-signer.yaml
  templates/portal/deployment.yaml
  templates/redis/statefulset.yaml
  templates/registry/registry-dpl.yaml
  templates/trivy/trivy-sts.yaml
  values.yaml
Labels: target/1.5.4

#877 fix: make the reference to the jobloggers array consistent
  README.md
  docs/High Availability.md
  templates/jobservice/jobservice-dpl.yaml
Labels: target/1.6.1

#905 Add another init container for database to ensure the permission of data directory
  templates/database/database-ss.yaml
Labels: target/1.6.1

#917 Bump up OSS Harbor to 2.2.1
  Chart.yaml
  values.yaml
Labels: target/1.6.1
