Repository goharbor/harbor-helm, pull requests merged in 2022-11, with the labels that each got.

#1337 Fix missing environment variable for registry container - Azure
  templates/registry/registry-dpl.yaml
Labels: target/1.11.0

#1339 [Cherry-pick] Fix missing environment variable for registry container - Azure
  templates/registry/registry-dpl.yaml
Labels: target/1.10.2

#1307 Allow to configure timeoutSeconds in livenessProbe and readinessProbe
  README.md
  templates/database/database-ss.yaml
  values.yaml
Labels: review/watch-list

#1338 Add JFrog Artifactory As Supported Proxy-Cache
  templates/core/core-cm.yaml
Labels: review/watch-list, target/1.11.0

#1317 Add support for F5 BIG-IP Ingress
  README.md
  templates/core/core-svc.yaml
  templates/notary/notary-svc.yaml
  templates/portal/service.yaml
  values.yaml
Labels: review/watch-list, target/1.11.0
