Repository goharbor/harbor-helm, pull requests merged in 2022-09, with the labels that each got.

#1278 Remove ssl_protocols TLSv1.1
  templates/nginx/configmap-https.yaml
Labels: target/1.3.14

#1293 update portal configMap of swagger
  templates/portal/configmap.yaml
Labels: target/1.11.0

#1288 Harbor Registry -- Fix existing secret reference in deployment
  templates/registry/registry-dpl.yaml
Labels: target/1.11.0, target/1.10.1

#1280 fix: README docs variable names & types
  README.md
Labels: target/1.11.0, target/1.10.1

#1298 [Cherry-pick] - Fix existing secret ref
  templates/registry/registry-dpl.yaml
Labels: target/1.10.1
