Repository goharbor/harbor-helm, pull requests merged in 2023-04, with the labels that each got.

#1447 feat: add configmap checksum annotation for portal
  templates/portal/deployment.yaml
Labels: target/1.12.0

#1475 feat: add config of reaper.max_update_hours & reaper.max_dangling_hours
  README.md
  templates/jobservice/jobservice-cm.yaml
  values.yaml
Labels: target/1.12.0

#1473 Bump up version to 1.12.0, appVersion to 2.8.0
  Chart.yaml
  values.yaml
Labels: target/1.12.0

#1474 feat: add config of reaper.max_update_hours & reaper.max_dangling_hours
  README.md
  templates/jobservice/jobservice-cm.yaml
  values.yaml
Labels: target/1.13.0

#1476 fix: update Library in Jenkinsfile for helm v1.12.0
  test/e2e/Jenkinsfile
Labels: target/1.12.0

#1477 feat: Upload Harbor 1.12.0 to chart repository
  harbor-1.12.0.tgz
  index.yaml
Labels: target/1.12.0

#1480 feat: add podLabels
  templates/core/core-dpl.yaml
  templates/database/database-ss.yaml
  templates/exporter/exporter-dpl.yaml
  templates/jobservice/jobservice-dpl.yaml
  templates/nginx/deployment.yaml
  templates/notary/notary-server.yaml
  templates/notary/notary-signer.yaml
  templates/portal/deployment.yaml
  templates/redis/statefulset.yaml
  templates/registry/registry-dpl.yaml
  templates/trivy/trivy-sts.yaml
  values.yaml
Labels: target/1.13.0

#1484 fix: github action
  .github/workflows/integration.yaml
Labels: target/1.11.2

#1483 Bump up version to 1.11.2, appVersion to 2.7.2
  Chart.yaml
  values.yaml
Labels: target/1.11.2

#1487 feat: Upload Harbor 1.11.2 to chart repository
  harbor-1.11.2.tgz
  index.yaml
Labels: target/1.11.2
