Repository goharbor/harbor-helm, pull requests merged in 2023-08, with the labels that each got.

#1569 feat: add customization on redis db
  README.md
  templates/_helpers.tpl
  templates/core/core-cm.yaml
  templates/jobservice/jobservice-cm-env.yaml
  values.yaml
Labels: target/1.13.0

#1570 (cherry-pick) feat: add customization on redis db
  README.md
  templates/_helpers.tpl
  templates/core/core-cm.yaml
  templates/jobservice/jobservice-cm-env.yaml
  values.yaml
Labels: target/1.12.4

#1571 Bump up version to 1.12.4, appVersion to 2.8.4
  Chart.yaml
  values.yaml
Labels: target/1.12.4

#1545 Add registryctl env secretRef for S3 existingSecret
  templates/registry/registry-dpl.yaml
Labels: target/1.13.0

#1579 Bump up version to 1.13.0, appVersion to 2.9.0
  Chart.yaml
  test/e2e/Jenkinsfile
  values.yaml
Labels: target/1.13.0

#1580 feat: Upload Harbor 1.13.0 to chart repository
  harbor-1.13.0.tgz
  index.yaml
Labels: target/1.13.0

#1590 fix: remove the previous released 1.13.0 from ArtifactHub
  harbor-1.13.0.tgz
  index.yaml
Labels: target/1.13.0

#1584 fix: add clusterIP.ports.httpsPort back
  values.yaml
Labels: target/1.14.0

#1585 [Cherry-pick] fix: add clusterIP.ports.httpsPort back
  values.yaml
Labels: target/1.13.0

#1586 [Cherry-pick] Add registryctl env secretRef for S3 existingSecret
  templates/registry/registry-dpl.yaml
Labels: target/1.12.5

#1587 [Cherry-pick] Add registryctl env secretRef for S3 existingSecret
  templates/registry/registry-dpl.yaml
Labels: target/1.11.3

#1588 fix: single qoutes for trace attributes
  templates/_helpers.tpl
Labels: target/1.12.5

#1589 [Cherry-pick] fix: single qoutes for trace attributes
  templates/_helpers.tpl
Labels: target/1.11.3
