Repository goharbor/harbor-helm, pull requests merged in 2023-02, with the labels that each got.

#1378 fix: remove scandata volume in jobservice
  README.md
  templates/_helpers.tpl
  templates/jobservice/jobservice-dpl.yaml
  templates/jobservice/jobservice-pvc-scandata.yaml
  values.yaml
Labels: target/1.12.0

#1379 [cherry-pick] fix: remove scandata volume in jobservice
  README.md
  templates/_helpers.tpl
  templates/jobservice/jobservice-dpl.yaml
  templates/jobservice/jobservice-pvc-scandata.yaml
  values.yaml
Labels: target/1.11.1

#1380 [Cherry-pick] fix: remove scandata volume in jobservice
  README.md
  templates/_helpers.tpl
  templates/jobservice/jobservice-dpl.yaml
  templates/jobservice/jobservice-pvc-scandata.yaml
  values.yaml
Labels: target/1.10.4

#1396 fix: github action
  .github/workflows/integration.yaml
Labels: target/1.12.0

#1400 feat: upgrade ci config version
  .github/workflows/integration.yaml
  .github/workflows/lint.yaml
  .github/workflows/unittest.yaml
Labels: target/1.12.0

#1405 feat: upgrade ci config version
  .github/workflows/integration.yaml
  .github/workflows/lint.yaml
  .github/workflows/unittest.yaml
Labels: target/1.11.1

#1406 feat: upgrade ci config version
  .github/workflows/integration.yaml
  .github/workflows/lint.yaml
  .github/workflows/unittest.yaml
Labels: target/1.10.4

#1407 feat: upgrade ci config version
  .github/workflows/integration.yaml
  .github/workflows/lint.yaml
  .github/workflows/unittest.yaml
Labels: target/1.9.6

#1403 add docs, values, and template updates to remove default tls key and …
  README.md
  cert/tls.crt
  cert/tls.key
  templates/core/core-secret.yaml
  templates/exporter/exporter-secret.yaml
  values.yaml
Labels: target/1.11.1

#1413 Bump up version to 1.11.1, appVersion to 2.7.1
  Chart.yaml
  values.yaml
Labels: target/1.11.1

#1410 add docs, values, and template updates to remove default tls key and …
  README.md
  cert/tls.crt
  cert/tls.key
  templates/core/core-secret.yaml
  templates/exporter/exporter-secret.yaml
  values.yaml
Labels: target/1.9.6

#1409 add docs, values, and template updates to remove default tls key and …
  README.md
  cert/tls.crt
  cert/tls.key
  templates/core/core-secret.yaml
  templates/exporter/exporter-secret.yaml
  values.yaml
Labels: target/1.10.4

#1412 fix: remove default tls keys
  README.md
  cert/tls.crt
  cert/tls.key
  templates/core/core-secret.yaml
  values.yaml
Labels: target/1.3.17
