Repository goharbor/harbor-helm, pull requests merged in 2023-07, with the labels that each got.

#1541 Fix grammar issue
  README.md
  values.yaml
Labels: target/1.13.0

#1543 add http2 strong_ssl_ciphers
  README.md
  templates/nginx/configmap-https.yaml
  templates/portal/configmap.yaml
  values.yaml
Labels: target/1.13.0

#1548 fix: get ingressControllerIP based on ingressControllerServiceType
  test/e2e/Jenkinsfile
Labels: target/1.13.0

#1553 feat: add the configuration for quota update provider
  README.md
  templates/core/core-cm.yaml
  values.yaml
Labels: target/1.13.0

#1558 [Cherry-pick] fix: get ingressControllerIP based on ingressControllerServiceType
  test/e2e/Jenkinsfile
Labels: target/1.12.3

#1559 [Cherry-pick] fix: get ingressControllerIP based on ingressControllerServiceType
  test/e2e/Jenkinsfile
Labels: target/1.11.3

#1560 Bump up version to 1.12.3, appVersion to 2.8.3
  Chart.yaml
  values.yaml
Labels: target/1.12.3

#1562 feat: Upload Harbor 1.12.3 to chart repository
  harbor-1.12.3.tgz
  index.yaml
Labels: target/1.12.3
