Repository goharbor/harbor-helm, pull requests merged in 2023-06, with the labels that each got.

#1515 Bump up version to 1.12.2, appVersion to 2.8.2
  Chart.yaml
  values.yaml
Labels: target/1.12.2

#1516 Bump up version to 1.3.19, appVersion 1.10.18
  Chart.yaml
  values.yaml
Labels: target/1.3.19

#1517 feat: Upload Harbor 1.3.19 to chart repository
  harbor-1.3.19.tgz
  index.yaml
Labels: target/1.3.19

#1518 feat: Upload Harbor 1.12.2 to chart repository
  harbor-1.12.2.tgz
  index.yaml
Labels: target/1.12.2

#1519 fix: update icon url
  Chart.yaml
Labels: target/1.3.20

#1528 Add tls checksum to exporter deployment
  templates/exporter/exporter-dpl.yaml
Labels: target/1.13.0
