Repository goharbor/harbor-helm, pull requests merged in 2023-12, with the labels that each got.

#1647 fix: quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION
  templates/core/core-cm.yaml
Labels: target/1.11.4

#1652 Bump up version to 1.11.4, appVersion to 2.7.4
  Chart.yaml
  values.yaml
Labels: target/1.11.4

#1623 feat(nginx): add an option to set static ip for clusterIP service
  README.md
  templates/nginx/service.yaml
  values.yaml
Labels: target/1.14.0

#1643 fix quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION
  templates/core/core-cm.yaml
Labels: target/1.14.0

#1648 fix: quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION
  templates/core/core-cm.yaml
Labels: target/1.12.5

#1649 fix: quote for ARTIFACT_PULL_ASYNC_FLUSH_DURATION
  templates/core/core-cm.yaml
Labels: target/1.13.2

#1650 Fix messy table in README
  README.md
Labels: target/1.14.0

#1654 feat: Upload Harbor 1.11.4 to chart repository
  harbor-1.11.4.tgz
  index.yaml
Labels: target/1.11.4

#1655 fix: update settings.cases order
  test/e2e/Jenkinsfile
Labels: target/1.14.0

#1646 fix: add REGISTRY_HTTP_SECRET env for registry if .Values.registry.existingSecret is set
  templates/registry/registry-dpl.yaml
Labels: target/1.14.0

#1662 Bump up version to 1.14.0, appVersion to 2.10.0
  Chart.yaml
  test/e2e/Jenkinsfile
  values.yaml
Labels: target/1.14.0

#1664 fix: update KUBECTL_VERSION && HELM_VERSION, and use wget instead of curl
  test/e2e/Dockerfile
Labels: target/1.15.0
