Repository goharbor/harbor-helm, pull requests merged in 2024-08, with the labels that each got.

#1787 Create unit tests for Core
  .github/workflows/unittest.yaml
  test/unittest/core_configmap_test.yaml
  test/unittest/core_deployment_test.yaml
  test/unittest/core_job_test.yaml
  test/unittest/core_secret_test.yaml
  test/unittest/core_svc_test.yaml
  test/unittest/core_tls_test.yaml
  test/unittest/trivy_stateful_set_test.go
  test/unittest/trivy_statefulset_test.yaml
Labels: review/watch-list

#1809 DOCS: missing link to distribution
  values.yaml
Labels: target/1.16.0

#1793 fix: update Jenkinsfile library to "harbor@2.11"
  test/e2e/Jenkinsfile
Labels: release-note/update

#1815 Bump up version to 1.15.1, appVersion to 2.11.1
  Chart.yaml
  values.yaml
Labels: target/1.15.1

#1816 feat: Upload Harbor 1.15.1 to chart repository
  harbor-1.15.1.tgz
  index.yaml
Labels: target/1.15.1
