Repository goharbor/harbor-helm, pull requests merged in 2024-02, with the labels that each got.

#1691 feat: Upload Harbor 1.13.2 to chart repository
  harbor-1.13.2.tgz
  index.yaml
Labels: target/1.13.2

#1693 Remove the key harbor section
  README.md
  templates/ingress/ingress.yaml
  values.yaml
Labels: target/1.15.0

#1495 Fix the exporter's containerPort
  templates/exporter/exporter-dpl.yaml
Labels: Stale

#1496 Fix the registry's containerPort
  templates/registry/registry-dpl.yaml
Labels: Stale

#1497 Fix the nginx's containerPort
  templates/nginx/deployment.yaml
Labels: release-note/update

#1270 feat: add checksum annotation for exporter
  templates/exporter/exporter-dpl.yaml
Labels: kind/requirement, release-note/update

#1717 feat: add trivy.skipJavaDBUpdate for configuring SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE
  README.md
  templates/trivy/trivy-sts.yaml
  values.yaml
Labels: target/1.15.0

#1718 feat: add trivy.skipJavaDBUpdate for configuring SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE
  README.md
  templates/trivy/trivy-sts.yaml
  values.yaml
Labels: target/1.14.1
