Repository goharbor/harbor-helm, pull requests merged in 2024-04, with the labels that each got.

#1740 Bump up version to 1.14.2, appVersion to 2.10.2
  Chart.yaml
  values.yaml
Labels: target/1.14.2

#1741 feat: Upload Harbor 1.14.2 to chart repository
  harbor-1.14.2.tgz
  index.yaml
Labels: target/1.14.2

#1732 Fix dead documentation link in values.yaml
  values.yaml
Labels: target/1.15.0, release-note/update

#1748 feat: Upload Harbor 1.13.4 to chart repository
  harbor-1.13.4.tgz
  index.yaml
Labels: release-note/ignore-for-release

#1749 add "harbor.legacy.labels" to resolve the upgrade issue 1747
  templates/_helpers.tpl
  templates/database/database-ss.yaml
  templates/redis/statefulset.yaml
  templates/trivy/trivy-sts.yaml
Labels: target/1.15.0, release-note/update

#1752 Bump up version to 1.12.6, appVersion to 2.8.6
  Chart.yaml
  values.yaml
Labels: release-note/update, target/1.12.6

#1753 feat: Upload Harbor 1.12.6 to chart repository
  harbor-1.12.6.tgz
  index.yaml
Labels: release-note/ignore-for-release
