Repository goharbor/harbor-helm, pull requests merged in 2024-01, with the labels that each got.

#1668 [cherry-pick] fix: update KUBECTL_VERSION && HELM_VERSION, and use wget instead of curl (#1664)
  test/e2e/Dockerfile
Labels: target/1.14.0

#1670 feat: Upload Harbor 1.14.0 to chart repository
  harbor-1.14.0.tgz
  index.yaml
Labels: target/1.14.0

#1669 Add harbor-helm release workflow
  .github/release.yml
  .github/workflows/publish_release.yaml
Labels: target/1.15.0

#1675 fix: avoid decoding plain text password when database secret exists
  templates/_helpers.tpl
Labels: needs/cherry-pick, target/1.15.0

#1679 [cherry-pick] fix: avoid decoding plain text password when database secret exists
  templates/_helpers.tpl
Labels: target/1.14.1

#1680 feat: add GDPR compliance for audit logs if a user is deleted
  README.md
  templates/core/core-cm.yaml
  values.yaml
Labels: target/1.15.0

#1681 [cherry-pick] feat: add GDPR compliance for audit logs if a user is deleted
  README.md
  templates/core/core-cm.yaml
  values.yaml
Labels: target/1.14.1

#1690 Bump up version to 1.13.2, appVersion to 2.9.2
  Chart.yaml
  values.yaml
Labels: target/1.13.2
