Repository goharbor/harbor-helm, pull requests merged in 2024-07, with the labels that each got.

#1784 Bump up version to 1.13.5, appVersion to 2.9.5
  Chart.yaml
  values.yaml
Labels: release-note/update, target/1.13.5

#1791 Bump up version to 1.14.3, appVersion to 2.10.3
  Chart.yaml
  values.yaml
Labels: target/1.14.3

#1794 feat: Upload Harbor 1.14.3 to chart repository
  harbor-1.14.3.tgz
  index.yaml
Labels: target/1.14.3

#1796 feat: Upload Harbor 1.13.5 to chart repository
  harbor-1.13.5.tgz
  index.yaml
Labels: target/1.13.5

#1792 fix: update maintainers info and comment of trivy config
  Chart.yaml
  README.md
  values.yaml
Labels: target/1.16.0

#1779 Fix ArgoCD integration by adding `metadata.namespace` to all templates
  templates/core/core-cm.yaml
  templates/core/core-dpl.yaml
  templates/core/core-pre-upgrade-job.yaml
  templates/core/core-secret.yaml
  templates/core/core-svc.yaml
  templates/core/core-tls.yaml
  templates/database/database-secret.yaml
  templates/database/database-ss.yaml
  templates/database/database-svc.yaml
  templates/exporter/exporter-cm-env.yaml
  templates/exporter/exporter-dpl.yaml
  templates/exporter/exporter-secret.yaml
  templates/exporter/exporter-svc.yaml
  templates/ingress/ingress.yaml
  templates/ingress/secret.yaml
  templates/internal/auto-tls.yaml
  templates/jobservice/jobservice-cm-env.yaml
  templates/jobservice/jobservice-cm.yaml
  templates/jobservice/jobservice-dpl.yaml
  templates/jobservice/jobservice-pvc.yaml
  templates/jobservice/jobservice-secrets.yaml
  templates/jobservice/jobservice-svc.yaml
  templates/jobservice/jobservice-tls.yaml
  templates/metrics/metrics-svcmon.yaml
  templates/nginx/configmap-http.yaml
  templates/nginx/configmap-https.yaml
  templates/nginx/deployment.yaml
  templates/nginx/secret.yaml
  templates/nginx/service.yaml
  templates/portal/configmap.yaml
  templates/portal/deployment.yaml
  templates/portal/service.yaml
  templates/portal/tls.yaml
  templates/redis/service.yaml
  templates/redis/statefulset.yaml
  templates/registry/registry-cm.yaml
  templates/registry/registry-dpl.yaml
  templates/registry/registry-pvc.yaml
  templates/registry/registry-secret.yaml
  templates/registry/registry-svc.yaml
  templates/registry/registry-tls.yaml
  templates/registry/registryctl-cm.yaml
  templates/registry/registryctl-secret.yaml
  templates/trivy/trivy-secret.yaml
  templates/trivy/trivy-sts.yaml
  templates/trivy/trivy-svc.yaml
  templates/trivy/trivy-tls.yaml
Labels: review/watch-list, target/1.16.0
