Repository goharbor/harbor-helm, pull requests merged in 2025-08, with the labels that each got.

#2223 update adapter list for replication and proxy-cache
  templates/core/core-cm.yaml
Labels: target/1.18.0

#2173 Fix ArgoCD sync
  templates/database/database-ss.yaml
  templates/redis/statefulset.yaml
  templates/trivy/trivy-sts.yaml
Labels: env/tools/argocd, needs/follow-up, target/1.18.0

#2212 feat: Added support for configuring dual-stack services
  README.md
  templates/core/core-svc.yaml
  templates/database/database-svc.yaml
  templates/exporter/exporter-svc.yaml
  templates/jobservice/jobservice-svc.yaml
  templates/nginx/service.yaml
  templates/portal/service.yaml
  templates/redis/service.yaml
  templates/registry/registry-svc.yaml
  templates/trivy/trivy-svc.yaml
  values.yaml
Labels: needs/follow-up, target/1.18.0
